# Generated by Django 4.2.1 on 2024-05-21 11:29

# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion


# class Migration(migrations.Migration):

#     dependencies = [
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#         ('hotels', '0002_booking_booking_date_booking_check_in_date_and_more'),
#     ]

#     operations = [
#         migrations.RenameField(
#             model_name='hotel',
#             old_name='city',
#             new_name='location',
#         ),
#         migrations.RemoveField(
#             model_name='hotel',
#             name='country',
#         ),
#         migrations.AddField(
#             model_name='booking',
#             name='check_out_date',
#             field=models.DateField(default=2),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='booking',
#             name='status',
#             field=models.CharField(default='Pending', max_length=20),
#         ),
#         migrations.AddField(
#             model_name='booking',
#             name='user',
#             field=models.ForeignKey(default=100.0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='hotel',
#             name='price_per_night',
#             field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
#             preserve_default=False,
#         ),
#         migrations.AlterField(
#             model_name='booking',
#             name='booking_date',
#             field=models.DateTimeField(auto_now_add=True),
#         ),
#         migrations.AlterField(
#             model_name='booking',
#             name='check_in_date',
#             field=models.DateField(),
#         ),
#         migrations.DeleteModel(
#             name='Room',
#         ),
#     ]


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_booking_booking_date_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(),
            preserve_default=False,  # Remove this line
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,  # Remove this line
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
